name: Deployment notification

on:
  deployment_status:

jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_CHANNEL: ci
    steps:
      - name: Test event
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - name: Notify success
      #   uses: bryan-nice/slack-notification@master
      #   if: needs.deploy.result == 'success'
      #   env:
      #     SLACK_TITLE: "Deploy success! 🎉"
      #     SLACK_MESSAGE: "${{ github.event.client_payload.ref }} was successfully deployed to ${{ github.event.client_payload.environment }}"
      # - name: Notify failure
      #   uses: bryan-nice/slack-notification@master
      #   if: needs.deploy.result == 'failure'
      #   env:
      #     SLACK_TITLE: "Deploy failed! 😬"
      #     SLACK_MESSAGE: "${{ github.event.client_payload.ref }} was not deployed to ${{ github.event.client_payload.environment }}"
