name: Notification

on:
  release:
    types:
      - created

jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_CHANNEL: ci
    steps:
      - name: Notify release
        uses: bryan-nice/slack-notification@master
        env:
          SLACK_TITLE: |
            Version <${{ github.event.release.html_url }}|`${{ github.event.release.tag_name }}`> was released 🚀
          SLACK_MESSAGE: |
            ${{ github.event.release.body }}
